Ammeter:
  enable: true
  item-id: 263
Bookcase:
  enable: true
  read-text: You pick up a book...
Bridge:
  enable: true
  redstone: true
  max-length: 30
  max-width: 5
  blocks:
  - 4
  - 5
  - 20
  - 43
Door:
  enable: true
  redstone: true
  max-length: 30
  max-width: 5
  blocks:
  - 4
  - 5
  - 20
  - 43
Gate:
  enable: true
  redstone: true
  blocks:
  - 85
  - 101
  - 102
  - 113
  limit-columns: true
  max-columns: 14
Elevator:
  enable: true
  loop-top-bottom: false
  allow-button-on-back: true
Teleporter:
  enable: true
  max-range: -1
  need-sign-destination: false
Cauldron:
  legacy-enable: false
  legacy-block: 1
  new-enable: true
  new-spoons: true
Lightstone:
  enable: true
  item-id: 348
Light Switch:
  enable: true
  max-range: 10
  max-lights: 20
Hidden Switch:
  enable: true
  any-side: true
Snow:
  piling-enable: true
  trample-enable: true
  placable-snow: true
  jump-trample-only: true
  pile-high: false
  realistic-piling: false
Toggle Areas:
  enable: true
  redstone: true
  max-areas-per-user: 30
  max-size-per-area: 5000
  use-schematic: true
Command Sign:
  enable: true
Custom Drops:
  enable: true
  require-permissions: false
Dispenser Recipes:
  enable: true
Chairs:
  enable: true
  sneaking: true
  blocks:
  - 53
  - 67
  - 108
  - 109
  - 114
  - 128
  - 134
  - 135
  - 136
  health-regen: true
AI Mechanics:
  enable: true
  realistic-zombie-vision: true
  skeleton-critical-shot: true
Chunk Anchor:
  enable: true
Cooking Pot:
  enable: true
  requires-fuel: false
  cooks-everything: false
  open-on-click: false
Custom Crafting:
  enable: true
Painting Settings:
  enable: true
XP Storer:
  enable: true
  block: 52
Map Changer:
  enable: true
Mechanisms:
  stop-mechanism-dupe: true
Payment Settings:
  enable: true